### ISSUE TITLE
Assignment 1 is ready for grading!

### ISSUE THREAD

**Issue by melmlr** [VIS-2129-F2020/melmiller-vis#1]
With great excitement, Assignment 1 is ready for your eyes. I'm looking forward to receiving your feedback. The html file (titled "Assignment 1_FINAL" can be viewed here: https://vis-2129-f2020.github.io/melmiller-vis/Assignment-1_FINAL

**Comment by bauranov** [comment]
Everything looks great, I have nothing to add. I really like the scatter plot without the dots. You can suppress warning messages by adding {r, warning=FALSE} at the beginning of the code chunk. Keep up the good work!
