### ISSUE TITLE
Assignment 2 is ready for grading

### ISSUE THREAD

**Issue by melmlr** [VIS-2129-F2020/melmiller-vis#2]
Assignment 2 is ready for grading. The .RMD file can be found [here](https://github.com/VIS-2129-F2020/melmiller-vis/blob/master/Assignment%202_FINAL.Rmd), and the html file can be found [here](https://vis-2129-f2020.github.io/melmiller-vis/Assignment-2_FINAL).

Thanks!
Mel

**Comment by bauranov** [comment]
Very good work! Everything looks great, I don't have any code-related comments. I would encourage you to experiment with different color palettes. Is there a specific reason why you started your breaks and labels at 80k?
