### ISSUE TITLE
Assignment 3 is ready for grading!

### ISSUE THREAD

**Issue by melmlr** [VIS-2129-F2020/melmiller-vis#3]
Hi! HTML file can be found [here](https://github.com/VIS-2129-F2020/melmiller-vis/blob/master/VIS-Assignment-3_FINAL.html), and the .Rmd file is [here](https://github.com/VIS-2129-F2020/melmiller-vis/blob/master/VIS-Assignment-3_FINAL.Rmd).

**Comment by bauranov** [comment]
Nicely done, keep up the good work.
