### ISSUE TITLE
Assignment 4 is ready for grading

### ISSUE THREAD

**Issue by melmlr** [VIS-2129-F2020/melmiller-vis#4]
Hi all - I think I'm having issues pushing files to GitHub. It looks like my files are uploading, but I'm having trouble linking to the direct HTML files. I'll try to figure this out asap, but in the meantime, you can (hopefully) view the .html file [here](https://vis-2129-f2020.github.io/melmiller-vis/VIS-Assignment-4_FINAL.html). Please let me know if you have trouble accessing the file.

Thank you.

**Comment by bauranov** [comment]
Everything looks good!
